version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sphinx
    versions:
    - "> 2.4.4"
